### DISCUSSION TITLE
Implement support for a "form" mode

### DISCUSSION THREAD

**Discussion by ChrisABryant** [josdejong/svelte-jsoneditor#261] [Ideas]
Looks far better than previous json editors we've used!  Color picker and boolean checkboxes were exactly what I was looking for.

Two things as we have a static structure that we only want to be able to change values and not schema. Used the following css with the jse-no-context class applied to the wrapper div.  This prevents display of the context menu as well as attempts to edit the object keys.  Would be nice if there were some prop flags for contextMenu and editableKeys. 

```css
.jse-no-context {

   .jse-contextmenu {
      display: none !important;
   }

   .jse-context-menu-pointer-anchor {
      display: none !important;
   }

   .jse-context-menu-pointer {
      display: none !important;
   }

   .jse-insert-area {
      display: none !important;
   }

   .jse-key {
      pointer-events: none;
      cursor: pointer;
   }

}
```
