### ISSUE TITLE
Using material icon font for buttons

### ISSUE THREAD

**Issue by dbauszus-glx** [josdejong/svelte-jsoneditor#532]
I had a look at a couple of issues in regards of adding icons from an icon font like material [Google] but didn't find any satisfactory answer. I was able to work this out and would like to share my approach which may help others.

I push a text type button into the items in the onRenderMenu method.

```js
items.push({
  type: 'button',
  className: 'material-symbols-outlined-forced',
  text: 'sync',
  title: 'Update Dataview',
  onClick: updateDataview,
});
```

The text content [eg [sync](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:sync:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%231f1f1f)] is the icon name.

I add a className for this text button.

I set the Material Symbols Outlined font-family as !important to overide the inherited font in the css class specificity.

```css
@import url(https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0,0);

.material-symbols-outlined-forced {
  font-family: 'Material Symbols Outlined' !important
}
```

![Image](https://github.com/user-attachments/assets/eaabf0b6-1ca3-4892-b27f-131e8d239a7a)
